-- ============================================================================
-- Funding Page Migration
-- Adds per-milestone notes + status fields, creates nonfunded_codes reference table
-- Run in Supabase SQL Editor
-- ============================================================================

-- Step 1: Add new columns to project_funding
ALTER TABLE public.project_funding ADD COLUMN IF NOT EXISTS m1_notes TEXT;
ALTER TABLE public.project_funding ADD COLUMN IF NOT EXISTS m2_notes TEXT;
ALTER TABLE public.project_funding ADD COLUMN IF NOT EXISTS m3_notes TEXT;
ALTER TABLE public.project_funding ADD COLUMN IF NOT EXISTS m1_status TEXT;
ALTER TABLE public.project_funding ADD COLUMN IF NOT EXISTS m2_status TEXT;
ALTER TABLE public.project_funding ADD COLUMN IF NOT EXISTS m3_status TEXT;

-- Step 2: Create nonfunded_codes reference table
CREATE TABLE IF NOT EXISTS public.nonfunded_codes (
  code TEXT PRIMARY KEY,
  master_code TEXT NOT NULL,
  description TEXT NOT NULL,
  responsible_party TEXT,
  reference TEXT
);

-- Step 3: RLS on nonfunded_codes
ALTER TABLE public.nonfunded_codes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "nf_codes_read" ON public.nonfunded_codes FOR SELECT TO authenticated USING (true);
CREATE POLICY "nf_codes_write" ON public.nonfunded_codes FOR ALL TO authenticated
  USING (public.auth_is_admin()) WITH CHECK (public.auth_is_admin());

-- Step 4: Seed nonfunded codes (218 codes)
INSERT INTO public.nonfunded_codes (code, master_code, description, responsible_party, reference) VALUES
  ('CANCELLED', 'Cancelled', 'account is cancelled', 'NA', NULL),
  ('ACH', 'Contract Error', 'ACH form has not been completed by customer', 'Sales Ops', 'CASH'),
  ('ADD', 'Contract Error', 'Address is incorrect on IA or in lender portal', 'Sales Ops', NULL),
  ('ADDER', 'Contract Error', 'An adder is listed on the IA but not Dividend OR we cannot confirm the adder happened.', 'Sales Ops', 'Dividend'),
  ('CLW', 'Contract Error', 'Conditional Lien Waiver needs to be signed by customer in Everbright for PPA', 'Sales Ops', 'Everbright'),
  ('CXLP', 'Contract Error', 'Loan cancelled in lender portal', 'Sales Ops', NULL),
  ('HCB', 'Contract Error', 'Need High cost breakdown from the Rep', 'Sales Ops', 'Goodleap'),
  ('HOA', 'Contract Error', 'Lender is requiring HOA approval Doc', 'Sales Ops', NULL),
  ('IA', 'Contract Error', 'Installation Agreement doesn''t match lender portal', 'Sales Ops', NULL),
  ('ITP', 'Contract Error', 'Infinity tranfer project needing to be transfer to TriSMART', 'Sales Ops', NULL),
  ('IPA', 'Contract Error', 'Installed panel amount does not match contract', 'Sales Ops', NULL),
  ('KW', 'Contract Error', 'Installed smaller system than promised', 'Sales Ops', NULL),
  ('LD', 'Contract Error', 'Customer needs to sign Lender docs', 'Sales Ops', NULL),
  ('NTP', 'Contract Error', 'Pending NTP in Lender portal', 'Sales Ops', NULL),
  ('PD', 'Contract Error', 'Contract prices do not match', 'Sales Ops', NULL),
  ('PT', 'Contract Error', 'Panel type in lender portal does not match install', 'Sales Ops', 'Dividend'),
  ('RR', 'Contract Error', 'Need to confirm Re-roof on lender contract', 'Sales Ops', NULL),
  ('RESIGN', 'Contract Error', 'legal contact signer has changed and project needs a resign', 'Sales Ops', NULL),
  ('STP', 'Contract Error', 'Account has stipulations. Not fundable until stips are cleared', 'Sales Ops', 'Sunlight'),
  ('UB', 'Contract Error', 'Lender requires Utility Bill', 'Sales Ops', NULL),
  ('WQU', 'Contract Error', 'Account quoted with wrong utility', 'Sales Ops', NULL),
  ('WU', 'Contract Error', 'Loan executed with a utility that is not approved', 'Sales Ops', NULL),
  ('HCO', 'Contract Error', 'Homeowner Change Order needs signature', 'Sales Ops', NULL),
  ('ICO', 'Contract Error', 'Installer Change Order needing to be signed by Helpdesk', 'Sales Ops', NULL),
  ('NCCO', 'Contract Error', 'Homeownder needs to sign No Cost Change Order', 'Sales Ops', NULL),
  ('WCN', 'Contract Error', 'Needs to complete welcome call with Lender', 'Sales Ops', 'Enfin'),
  ('ELE', 'Electrical Completion', 'Electrical completion more than 3 months out', 'Project Management', NULL),
  ('CRS', 'Customer Escalation', 'Customer refusing to sign Documents', 'Customer Service', NULL),
  ('CRW', 'Customer Escalation', 'Customer refusing work', 'Customer Service', NULL),
  ('HOLD', 'Customer Escalation', 'Account on hold', 'Customer Service', NULL),
  ('TT', 'Customer Service', 'Needs Tree trimming for PPA', 'Customer Service', NULL),
  ('DM', 'Damages', 'Customer has damages and won''t pay', 'Customer Service', 'CASH'),
  ('LEGAL', 'Customer Escalation', 'Escalated to legal- customer refuses to pay', 'LEGAL', NULL),
  ('ESM', 'Everbright', 'Everbright System Access', 'Funding', 'Everbright'),
  ('OSM', 'Everbright', 'Omnidian System Access', 'Funding', 'Everbright'),
  ('EJK', 'Everbright', 'Emailed Joe Kelly for rejection issue', 'Funding', 'Everbright'),
  ('ASR', 'Engineering', 'Shade study below threshold', 'Design', NULL),
  ('ENG', 'Engineering', 'Need new engineering', 'Design', 'Everbright'),
  ('LYD', 'Engineering', 'Panel layout in live project does not match install layout', 'Design', 'Everbright'),
  ('S28W', 'Engineering', 'Module Model is wrong in lender portal- needs to live project updated', 'Design', 'Everbright'),
  ('MOD', 'Engineering', 'Model in portal is incorrect.', 'Design', 'ALL'),
  ('SS', 'Engineering', 'Everbright rejected the Shade Study due to Aurora not matching their quote', 'Design', 'Everbright'),
  ('DC', 'Installation Issues', 'was not installed with domestic content.', 'Field Ops', 'Goodleap'),
  ('EXP', 'Expired', 'Credit App Expired', 'Sales Ops', NULL),
  ('FIN-ALL', 'Final', 'Lender Needs PTO and Inspection doc for Final Payment', 'Project Management', 'ALL'),
  ('FIN-IPD', 'FINAL-PM', 'Lender Needs inspection passed document for Final Payment', 'Project Management', 'ALL'),
  ('FIN-PTO', 'Final', 'Lender Needs PTO  for Final Payment', 'Project Management', 'ALL'),
  ('IPD-P', 'FINAL-PM', 'Inspection has passed and proof needs to be uploaded to Financier', 'Project Management', 'ALL'),
  ('IPD-MP', 'FINAL-PM', 'Inspection has passed and the permit is missing to prove address.', 'Project Management', 'ALL'),
  ('IPD-I', 'FINAL-PM', 'POPI has been rejected by Financier and needs either address or date.', 'Project Management', NULL),
  ('PTO-P', 'FINAL-PM', 'PTO has been issued and needs to be uploaded to financier', 'Project Management', 'ALL'),
  ('PTO-I', 'FINAL-PM', 'PTO letter has been rejected by Financier and needs either address or date.', 'Project Management', NULL),
  ('PTO-A', 'FINAL-PM', 'Needs PTO application submitted to financier', 'Project Management', 'ALL'),
  ('ICA', 'FINAL-PM', 'Needs Interconnection Agreement signed by utility and customer', 'Project Management', 'ALL'),
  ('Permit', 'FINAL-PM', 'Missing approved Permit application', 'Project Management', NULL),
  ('NF', 'Customer Escalation', 'Net funded (Customer escalation or Delayed PTO)', 'Project Management', NULL),
  ('CO', 'Funding', 'Customer needs to sign change order', 'Funding', 'ALL'),
  ('NMT', 'Funding', 'checked system and not showing correctly, need to review again to give time to update', 'Funding', 'EverBright'),
  ('IDK', 'Funding', 'Reaching out to other departments for guidance', 'Funding', NULL),
  ('HNR', 'Funding', 'Have not reviewed- pending submission of Substantial', 'Funding', NULL),
  ('ELC', 'Electrical Completion', 'Requires Electrical completion to Fund', 'Field Ops', 'ALL'),
  ('HDK', 'Equipment Issues', 'Needs hold down kit', 'Field Ops', 'ALL'),
  ('EES', 'Installation Issues', 'Lender requires separate Envoy systems for add-on panels', 'Field Ops', 'ALL'),
  ('ACW', 'Installation Issues', 'AC Combiner can not be installed with conduit through the top. Side and bottom only.', 'Field Ops', 'ALL'),
  ('BDE', 'Installation Issues', 'Battery installation Issue', 'Field Ops', 'ALL'),
  ('MSR', 'Installation Issues', 'Monitoring Specification rejected: Duracell configuration is incomplete', 'Field Ops', 'ALL'),
  ('BR', 'Installation Issues', 'Breaker installed is not an Eaton Breaker. Needs to be replaced', 'Field Ops', 'ALL'),
  ('BT', 'Installation Issues', 'Needs Battery installed', 'Field Ops', 'ALL'),
  ('CM', 'Installation Issues', 'Missing CELL MODEM installation', 'Field Ops', 'ALL'),
  ('CT', 'Installation Issues', 'CTs not properly installed or Missing', 'Field Ops', 'ALL'),
  ('ELCO', 'Installation Issues', 'Need Electrical corrections', 'Field Ops', 'ALL'),
  ('ENL', 'Installation Issues', 'Incomplete Commissioning', 'Field Ops', 'ALL'),
  ('FR', 'Installation Issues', 'Flat roof, pending tilt leg installation', 'Field Ops', 'ALL'),
  ('LST', 'Installation Issues', 'Needs Line Side Tap', 'Field Ops', 'ALL'),
  ('MC', 'Installation Issues', 'Needs Midclamps swapped', 'Field Ops', 'ALL'),
  ('MIBS', 'Installation Issues', 'redesign system to have a max of 19 inverters per battery by shedding.', 'Field Ops', 'ALL'),
  ('MNM', 'Installation Issues', 'Microinverters not matching', 'Field Ops', 'ALL'),
  ('MNSI', 'Installation Issues', 'Microinverters not scanned in, amount of micros do not match what was installed.', 'Field Ops', 'ALL'),
  ('MNR', 'Installation Issues', 'Microinverter(s) not reporting', 'Field Ops', 'ALL'),
  ('MPU', 'Installation Issues', 'Needs MPU installed', 'Field Ops', 'ALL'),
  ('MRA-OFF', 'Installation Issues', 'System is not reporting but is in service', 'Field Ops', 'ALL'),
  ('NMPMT', 'Installation Issues', 'Needs more panels to meet tolerance', 'Field Ops', 'ALL'),
  ('FLSH', 'Installation Issues', 'Needs Flashing corrected.', 'Field Ops', 'ALL'),
  ('MSM', 'Installation Issues', 'MICROINVERTER SERIAL map does not match install', 'Field Ops', 'ALL'),
  ('TILT', 'Installation Issues', 'Tilt is below 5°', 'Field Ops', 'ALL'),
  ('RNP', 'Installation Issues', 'Racking is not installed properly', 'Field Ops', 'ALL'),
  ('ST', 'Installation Issues', 'Needs Solar Stacks replaced with AVL equipment', 'Field Ops', 'ALL'),
  ('L2L', 'Installation Issues', 'Needs main breaker on sub panel', 'Field Ops', 'ALL'),
  ('IEJ', 'Installation Issues', 'Installation of expanding joints on underground pipe needed for city', 'Field Ops', 'ALL'),
  ('ABBW', 'Installation Issues', 'Contactor not properly wired through control port.', 'Field Ops', 'ALL'),
  ('RMA', 'Installation Issues', 'Equipment needs replaced', 'Field Ops', NULL),
  ('PCO', 'Installation Issues', 'Panel Count does not match plans', 'Field Ops', NULL),
  ('ABI', 'Monitoring', 'Array Builder incomplete', 'Monitoring', NULL),
  ('GWI', 'Monitoring', 'Gateway issue', 'Monitoring', NULL),
  ('SPO', 'Monitoring', 'System needs to be powered on/ Has PTO', 'Monitoring', NULL),
  ('ABDNM', 'Monitoring', 'Array Builder does not match layout', 'Monitoring', NULL),
  ('NEG', 'Monitoring', 'There is negative consumption data showing in the Graph Tab and there should not be.', 'Monitoring', NULL),
  ('SNS', 'Monitoring', 'Enlighten Site needs to be sperated.', 'Monitoring', 'EverBright'),
  ('CTLO', 'Monitoring', 'Consumption Meter needs to be set to Load Only', 'Monitoring', NULL),
  ('CTLS', 'Monitoring', 'Consumption Meter needs to be set to Load with Solar Production', 'Monitoring', NULL),
  ('CTM', 'Monitoring', 'CT Measurement Issues- FINAL', 'Monitoring', NULL),
  ('SPI', 'Monitoring', 'System Production Issue', 'Monitoring', NULL),
  ('ECT', 'Monitoring', 'Enable CTs (Both/Production/Consumption', 'Monitoring', NULL),
  ('MI', 'Monitoring', 'Monitoring Issue in portal (Alerts present)', 'Monitoring', NULL),
  ('SEW', 'Monitoring', 'Missing Solar Edge Warranty', NULL, NULL),
  ('MP', 'Monitoring', 'Missing access in Portal', 'Monitoring', NULL),
  ('BP', 'Not Loan', 'Build Partner- not financed, will be invoiced', 'Accounting', NULL),
  ('C', 'Not Loan', 'Cash Customer', 'Accounting', NULL),
  ('RI', 'Not Loan', 'Re-install pushed through the pipeline. There is no funding', 'Accounting', NULL),
  ('CHECK', 'Payment- Check', 'Customer is mailing a check', 'Accounting', 'CASH'),
  ('C2-D', 'Payment- Drafted', '2nd Cash payment has been drafted but has not cleared the bank account', 'Accounting', 'CASH'),
  ('C1', 'Payment- Pending', '1st Cash payment has not been drafted', 'Accounting', 'CASH'),
  ('C2-P', 'Payment- Pending', '2nd Cash payment Pending- will be drafted within 48 hours', 'Accounting', 'CASH'),
  ('INV', 'Payment- Pending', 'Cx refused to sign ACH. Invoice for payment has been sent.', 'Sales Ops', 'CASH'),
  ('PTO', 'Payment- Pending', 'Cash customer refusing to pay until PTO', 'Project Management', NULL),
  ('FUND', 'Payment- Pending', 'Paykeeper project not fully funded', 'Sales Ops', NULL),
  ('ABB', 'Photos', 'Missing photo showing ABB Contactor with rating visible', 'Field Ops', NULL),
  ('ALL', 'Photos', 'Missing ALL photos', 'Field Ops', 'ALL'),
  ('B1', 'Photos', 'Missing ALL BATTERY PHOTOS', 'Field Ops', 'ALL'),
  ('B2', 'Photos', 'Missing Battery Layout photos with clearances', 'Field Ops', 'ALL'),
  ('B2F', 'Photos', 'Missing Battery Layout photos showing the feet located at the bottom of the battery', 'Field Ops', 'ALL'),
  ('B2C', 'Photos', 'Battery Layout photos doesn''t properly show all Clearances', 'Field Ops', 'ALL'),
  ('B3', 'Photos', 'Missing Backup and non-backup loads panels', 'Field Ops', 'ALL'),
  ('B4', 'Photos', 'Missing Consumption and Production CTs', 'Field Ops', 'ALL'),
  ('B5', 'Photos', 'Missing Generation panel or internal panelboard', 'Field Ops', 'ALL'),
  ('B6', 'Photos', 'Missing Powerwall Connections', 'Field Ops', 'ALL'),
  ('B7', 'Photos', 'Missing/illegible Serial Number for Battery', 'Field Ops', 'ALL'),
  ('B8', 'Photos', 'Missing Serial Number for Gateway', 'Field Ops', 'ALL'),
  ('B9', 'Photos', 'Tesla portal reporting no Powerwall communications', 'Field Ops', 'ALL'),
  ('B10', 'Photos', 'Missing Critical Load Panel, with loads labelled and its main OCPD', 'Field Ops', 'ALL'),
  ('B11', 'Photos', 'Missing the tesla wizard screenshots of the wifi/cellular connection and the X for no battery grid charging', 'Field Ops', 'ALL'),
  ('B12', 'Installation Issues', 'Please provide access to battery portal', 'Field Ops', 'ALL'),
  ('B13', 'Photos', 'Please show the tesla powerwall cabinet with the resistor and the drain wire grounded installed in the same cabinet', 'Field Ops', 'ALL'),
  ('B14', 'Installation Issues', 'Please make sure red L2 wires are on top for the breakers on the busbar in the gateway', 'Field Ops', 'ALL'),
  ('B15', 'Installation Issues', 'Please show commissioning screenshots', 'Field Ops', 'ALL'),
  ('B16', 'Photos', 'Missing images of the relays/transformers', 'Field Ops', 'ALL'),
  ('B17', 'Photos', 'Missing photo of the contactor model number', 'Field Ops', 'ALL'),
  ('B18', 'Photos', 'Missing or blurry System controller (gateway) photo', 'Field Ops', 'ALL'),
  ('B19', 'Photos', 'Missing photo of Noise Filter', 'Field Ops', 'ALL'),
  ('B20', 'Photos', 'Missing BMS connections', 'Field Ops', 'Solrite'),
  ('B21', 'Photos', 'Missing/incomplete Grid, Microgrid, & DC connections', 'Field Ops', 'Solrite'),
  ('B22', 'Photos', 'Missing/incomplete Utility Profile config screenshot', 'Field Ops', 'Solrite'),
  ('B23', 'Photos', 'Missing/incomplete Battery registration screenshots', 'Field Ops', 'Solrite'),
  ('B24', 'Photos', 'Missing mounting plate photo', 'Field Ops', 'Solrite'),
  ('B25', 'Photos', 'Missing/incomplete CT configuration screenshots', 'Field Ops', 'Solrite'),
  ('B26', 'Photos', 'Missing photo of DTU placement.', 'Field Ops', 'Solrite'),
  ('B27', 'Photos', 'Missing photo of shutdown switch.', 'Field Ops', 'Enphase'),
  ('B28', 'Photos', 'Wifi Extender label clearly showing the model', 'Field Ops', 'Solrite'),
  ('B29', 'Photos', 'Missing TP Link Location Photo', 'Field Ops', 'Solrite'),
  ('B30', 'Photos', 'Missing SolarEdge Backup Interface sticker label', 'Field Ops', 'ALL'),
  ('B31', 'Photos', 'Missing SolarEdge Backup Interface wiring photo', 'Field Ops', 'ALL'),
  ('B32', 'Photos', 'Need photo of "Subpanel" connected to labeled existing breaker in loads panel', 'Field Ops', 'Solrite'),
  ('B33', 'Photos', 'AC Hub sticker', 'Field Ops', 'Solrite'),
  ('B34', 'Installation Issues', 'J1 jumper is improperly spliced on multi-battery installation', 'Field Ops', 'Solrite'),
  ('B35', 'Installation Issues', 'PC-PRO-WL photos needed including the HOST & CLIENT labels and install wiring', 'Field Ops', 'Solrite'),
  ('RGM', 'Installation Issues', 'RGM BOX opened, showing the ethernet wiring, meter turned on, showing green lights in both CTs.', 'Field Ops', 'Solrite'),
  ('DTU', 'Installation Issues', 'DTU needed for single sonnen battery installation', 'Field Ops', 'Solrite'),
  ('ATS', 'Installation Issues', 'Missing ATS internals', 'Field Ops', 'Solrite'),
  ('S1', 'Photos', 'No ARRAY photos uploaded', 'Field Ops', 'ALL'),
  ('S2', 'Photos', 'Incomplete ARRAY photos', 'Field Ops', 'ALL'),
  ('S3', 'Photos', 'Missing MODULE ATTACHMENT photo', 'Field Ops', 'ALL'),
  ('S4', 'Photos', 'Incomplete TILT Photos', 'Field Ops', 'ALL'),
  ('S5', 'Photos', 'Illegible TILT photos', 'Field Ops', 'ALL'),
  ('S6', 'Photos', 'Missing ROOF UNDERNEATH ARRAY photo', 'Field Ops', 'ALL'),
  ('S7', 'Photos', 'ROOF UNDERNEATH ARRAY photo shows poor wire management', 'Field Ops', 'ALL'),
  ('S8', 'Photos', 'Missing FLASHING photo', 'Field Ops', 'ALL'),
  ('S9', 'Photos', 'Missing STRUCTURAL photo', 'Field Ops', 'ALL'),
  ('S10', 'Photos', 'Missing ROOF J-BOX/CONDUIT ENTRANCE photo', 'Field Ops', 'ALL'),
  ('S11', 'Photos', 'Missing CONDUIT RUN photo', 'Field Ops', 'ALL'),
  ('S12', 'Photos', 'Missing CONDUIT PENETRATION photo', 'Field Ops', 'ALL'),
  ('S13', 'Photos', 'Missing HOME RUN CONDUIT photo', 'Field Ops', 'ALL'),
  ('S14', 'Photos', 'Missing AC COMBINER PANEL photo (With wiring exposed)', 'Field Ops', 'ALL'),
  ('S15', 'Photos', 'Missing/Illegible AC COMBINER PANEL photo', 'Field Ops', 'ALL'),
  ('S16', 'Photos', 'Missing MICROINVERTERS photo', 'Field Ops', 'ALL'),
  ('S17', 'Photos', 'Missing MICROINVERTER SERIAL # map photos', 'Field Ops', 'ALL'),
  ('S18', 'Photos', 'Illegible MICROINVERTER SERIAL # map photos', 'Field Ops', 'ALL'),
  ('S19', 'Photos', 'Missing AC DISCONNECT photos', 'Field Ops', 'ALL'),
  ('S20', 'Photos', 'Illegible FUSE RATING INSIDE AC DISCONNECT', 'Field Ops', 'ALL'),
  ('S20W', 'Installation Issues', 'Fuses inside AC disconnect do not match.', 'Field Ops', 'All'),
  ('S21', 'Photos', 'Missing ENVOY SERIAL # photo', 'Field Ops', 'ALL'),
  ('S22', 'Photos', 'Illegible ENVOY SERIAL # photo', 'Field Ops', 'ALL'),
  ('S23', 'Photos', 'Missing INTERCONNECTION photos', 'Field Ops', 'ALL'),
  ('S24', 'Photos', 'Missing UP CLOSE OF MAIN BREAKER photo', 'Field Ops', 'ALL'),
  ('S25', 'Photos', 'Missing UP CLOSE OF BACKFEED BREAKER photo', 'Field Ops', 'ALL'),
  ('S26', 'Photos', 'Missing BUS BAR RATING STICKER photo', 'Field Ops', 'ALL'),
  ('S28', 'Photos', 'Missing/illegible Back of Panel Photo', 'Field Ops', 'ALL'),
  ('S29', 'Photos', 'Missing trenching and concrete footing with depth measurements satisfying NEC 300', 'Field Ops', 'ALL'),
  ('S30', 'Photos', 'Missing house street number photo', 'Field Ops', 'ALL'),
  ('S31', 'Photos', 'Missing photo of the EGC bonded to rails or mounting structure.', 'Field Ops', 'EverBright'),
  ('S32', 'Photos', 'Missing Skeleton Racking photos', 'Field Ops', 'ALL'),
  ('S33', 'Photos', 'Missing photo of deadfront on MSP and labeled showing filler plates installed', 'Field Ops', 'EverBright'),
  ('S34', 'Photos', 'Missing photo of main service panel without deadfront to confirm CTs installed', 'Field Ops', 'ALL'),
  ('S35', 'Photos', 'Missing Electrical Wall photo', 'Field Ops', 'ALL'),
  ('S36', 'Photos', 'Missing AC Disconnect front panel photo', 'Field Ops', 'ALL'),
  ('S37', 'Photos', 'photo of Microinverter mounted to the panel', 'Field Ops', 'ALL'),
  ('S38', 'Photos', 'missing AHJ Required Grounding', 'Field Ops', 'Sunraise'),
  ('S39', 'Photos', 'Phase Verification in String Inverter (Circuit Testing)', 'Field Ops', 'Enfin'),
  ('S40', 'Photos', 'Missing Array String Map', 'Field Ops', 'Sunraise'),
  ('S41', 'Photos', 'Missing photo of Jbox Sealant', 'Field Ops', 'Sunraise'),
  ('S42', 'Photos', 'Missing inside of exterior mounted Main breaker enclosure', 'Field Ops', 'Solrite'),
  ('S43', 'Photos', 'Missing inside of non-back up loads panel', 'Field Ops', 'Solrite'),
  ('S44', 'Photos', 'Missing Ground-based Inverter label photo', 'Field Ops', 'Solrite'),
  ('S45', 'Photos', 'Missing Commissioning screenshots', 'Field Ops', 'ALL'),
  ('S46', 'Photos', 'Missing photo of the SIDE of the optimizer showing serial # & sku label', 'Field Ops', 'ALL'),
  ('BSI', 'Installation Issues', 'Battery Showing Issue', 'Field Ops', NULL),
  ('S-CS', 'Electrical Completion', 'Solrite- Conditionally submitted', 'Field Ops', 'Solrite'),
  ('WP', 'Installation Issues', 'Panel installed is not approved under Lender AVL', 'Field Ops', NULL),
  ('FWA', 'Funding', 'Pending sunraise approval to submit M3', 'Funding', 'Sunraise'),
  ('BLW', 'Installation Issues', 'Battery location is not acceptable w guidelines', 'Field Ops', NULL),
  ('PPD', 'Sunnova', 'Permit package design submitted to confirm Quote accuracy- waiting for response (typically 24hr turn around)', 'Funding', 'Sunnova'),
  ('SCO', 'Sunnova', 'Sunnova Change Order error- pending Sunnova IT ticket resolution', 'Funding', 'Sunnova'),
  ('SUB', 'Sunnova', 'Submitted in lender portal', 'Funding', NULL),
  ('TU-C', 'Sunnova - TU', 'TU pending Change order to be sent', 'Sunnova', 'Sunnova'),
  ('TU-P', 'Sunnova - TU', 'TU pending portal update', 'Sunnova', 'Sunnova'),
  ('TU-S', 'Sunnova - TU', 'TU pending customer signature', 'Sunnova', 'Sunnova'),
  ('OI', 'True-Up', 'Needs O&I Site Assessment Confirmation in Sunnova', 'Design', 'Sunnova'),
  ('TU', 'True-Up', 'Needs true- up form for O&I change order in Sunnova', 'Design', 'Sunnova'),
  ('CP', 'Funding', 'Needs Commissioning Package resubmitted', 'Funding', 'Sunnova')
ON CONFLICT (code) DO NOTHING;

-- ============================================================================
-- Done! Verify: SELECT count(*) FROM nonfunded_codes;
-- ============================================================================
