import type { ExistingSystem, TargetSystem, Results, StringConfig } from './types'

// ── SINGLE-LINE DIAGRAM (Engineering Plan Set Style) ────────────────────────

export function SingleLineDiagram({ existing, target, results }: {
  existing: ExistingSystem; target: TargetSystem; results: Results
}) {
  // Group strings by inverter — split evenly across inverters (e.g. 5 strings → 3 + 2)
  const stringsByInverter: StringConfig[][] = Array.from({ length: target.inverterCount }, () => [])
  const totalStrings = results.stringConfigs.length
  const basePerInv = Math.floor(totalStrings / target.inverterCount)
  const extraInvs = totalStrings % target.inverterCount
  let strIdx = 0
  for (let inv = 0; inv < target.inverterCount; inv++) {
    const count = basePerInv + (inv < extraInvs ? 1 : 0)
    for (let j = 0; j < count; j++) {
      if (strIdx < totalStrings) stringsByInverter[inv].push(results.stringConfigs[strIdx++])
    }
  }
  const battsPerStack = target.batteriesPerStack
  const W = 1400
  const H = 1050

  // Wire annotation helper
  const WireLabel = ({ x, y, text, rotate }: { x: number; y: number; text: string; rotate?: number }) => (
    <text x={x} y={y} fontSize="5.5" fill="#444" fontStyle="italic"
      transform={rotate ? `rotate(${rotate},${x},${y})` : undefined}>{text}</text>
  )

  // Breaker symbol: two angled lines meeting at contact point
  const Breaker = ({ x, y, label, amps }: { x: number; y: number; label?: string; amps?: string }) => (
    <g>
      <line x1={x} y1={y - 8} x2={x} y2={y - 2} stroke="#111" strokeWidth="1.5" />
      <line x1={x} y1={y - 2} x2={x + 5} y2={y + 6} stroke="#111" strokeWidth="1.5" />
      <line x1={x} y1={y + 8} x2={x} y2={y + 14} stroke="#111" strokeWidth="1.5" />
      <circle cx={x} cy={y - 2} r="1.5" fill="#111" />
      {label && <text x={x + 10} y={y + 2} fontSize="5.5" fill="#111">{label}</text>}
      {amps && <text x={x + 10} y={y + 9} fontSize="5" fill="#666">{amps}</text>}
    </g>
  )

  // Disconnect symbol
  const Disconnect = ({ x, y, label }: { x: number; y: number; label: string }) => (
    <g>
      <line x1={x} y1={y - 6} x2={x} y2={y} stroke="#111" strokeWidth="1.5" />
      <line x1={x} y1={y} x2={x + 6} y2={y - 8} stroke="#111" strokeWidth="2" />
      <circle cx={x} cy={y} r="2" fill="none" stroke="#111" strokeWidth="1" />
      <line x1={x} y1={y + 2} x2={x} y2={y + 8} stroke="#111" strokeWidth="1.5" />
      <text x={x + 10} y={y + 2} fontSize="5.5" fill="#111">{label}</text>
    </g>
  )

  return (
    <svg id="sld-svg" viewBox={`0 0 ${W} ${H}`} className="w-full" style={{ minWidth: 900, fontFamily: 'Arial, Helvetica, sans-serif' }}>
      <rect width={W} height={H} fill="white" />

      {/* ── DRAWING BORDER ── */}
      <rect x="4" y="4" width={W - 8} height={H - 8} fill="none" stroke="#111" strokeWidth="2" />
      <rect x="8" y="8" width={W - 16} height={H - 16} fill="none" stroke="#111" strokeWidth="0.5" />

      {/* ── TITLE BLOCK (bottom right) ── */}
      <rect x={W - 300} y={H - 100} width={290} height={90} fill="none" stroke="#111" strokeWidth="1" />
      <line x1={W - 300} y1={H - 80} x2={W - 10} y2={H - 80} stroke="#111" strokeWidth="0.5" />
      <line x1={W - 300} y1={H - 60} x2={W - 10} y2={H - 60} stroke="#111" strokeWidth="0.5" />
      <line x1={W - 300} y1={H - 40} x2={W - 10} y2={H - 40} stroke="#111" strokeWidth="0.5" />
      <text x={W - 155} y={H - 85} textAnchor="middle" fontSize="10" fontWeight="bold">ELECTRICAL SINGLE LINE DIAGRAM</text>
      <text x={W - 280} y={H - 67} fontSize="6" fill="#666">PROJECT:</text>
      <text x={W - 240} y={H - 67} fontSize="7" fontWeight="bold">{existing.projectName.toUpperCase()}</text>
      <text x={W - 280} y={H - 48} fontSize="6" fill="#666">ADDRESS:</text>
      <text x={W - 240} y={H - 48} fontSize="7">{existing.address.toUpperCase()}</text>
      <text x={W - 280} y={H - 28} fontSize="6" fill="#666">SYSTEM:</text>
      <text x={W - 240} y={H - 28} fontSize="6">{results.newTotalPanels} x {target.panelWattage}W = {results.newSystemDc} kW DC / {target.inverterCount} x 15kW INV / {results.newTotalStorage} kWh BESS</text>
      <text x={W - 280} y={H - 15} fontSize="5" fill="#999">GENERATED BY MicroGRID — FOR PE REVIEW ONLY — NOT FOR CONSTRUCTION</text>

      {/* ── STC BOX (top left) ── */}
      <rect x="20" y="16" width="200" height="45" fill="none" stroke="#111" strokeWidth="1" />
      <text x="30" y="30" fontSize="7" fontWeight="bold">STC</text>
      <text x="30" y="41" fontSize="6">MODULES: {results.newTotalPanels} x {target.panelWattage} = {results.newSystemDc} kW DC</text>
      <text x="30" y="51" fontSize="6">INVERTER(S): {target.inverterCount} x 15000 = {target.inverterCount * 15}.000 kW AC</text>

      {/* ── METER / ESID BOX (top center) ── */}
      <rect x="240" y="16" width="220" height="35" fill="none" stroke="#111" strokeWidth="1" />
      <text x="250" y="30" fontSize="6">METER NUMBER: 88 353 523</text>
      <text x="250" y="42" fontSize="6">ESID NUMBER: 1008901020901254810117</text>

      {/* ── PV ARRAYS (top, y=80-300) ── */}
      {Array.from({ length: target.inverterCount }, (_, inv) => {
        const strings = stringsByInverter[inv] ?? []
        const baseX = inv === 0 ? 40 : 720
        const moduleW = 8
        const moduleH = 14

        return (
          <g key={`arr-${inv}`}>
            {strings.map((sc, si) => {
              const sy = 95 + si * 50
              const roofLabel = sc.roofFaceIndex >= 0 ? `ROOF #${sc.roofFaceIndex + 1}` : ''

              return (
                <g key={si}>
                  {/* Module array - individual panel rectangles */}
                  {Array.from({ length: Math.min(sc.modules, 14) }, (_, mi) => (
                    <rect key={mi} x={baseX + mi * (moduleW + 1)} y={sy}
                      width={moduleW} height={moduleH} fill="none" stroke="#111" strokeWidth="0.7" />
                  ))}
                  {/* Series connection line through panels */}
                  <line x1={baseX} y1={sy + moduleH / 2}
                    x2={baseX + Math.min(sc.modules, 14) * (moduleW + 1) - 1} y2={sy + moduleH / 2}
                    stroke="#111" strokeWidth="0.3" strokeDasharray="1,2" />

                  {/* String label */}
                  <text x={baseX} y={sy - 4} fontSize="6" fontWeight="bold">
                    STRING {si + 1}: ({sc.modules}) {target.panelModel.toUpperCase()}
                  </text>
                  <text x={baseX + 200} y={sy - 4} fontSize="5.5" fill="#666">
                    {roofLabel}
                  </text>

                  {/* RSD label */}
                  <text x={baseX} y={sy + moduleH + 10} fontSize="5" fill="#444">
                    (N) RSD-D-20 ROOFTOP MODULE LEVEL RAPID SHUTDOWN DEVICE
                  </text>

                  {/* Wire from string right */}
                  <line x1={baseX + Math.min(sc.modules, 14) * (moduleW + 1) + 10} y1={sy + moduleH / 2}
                    x2={baseX + Math.min(sc.modules, 14) * (moduleW + 1) + 30} y2={sy + moduleH / 2}
                    stroke="#111" strokeWidth="1" />

                  {/* Voltage/current annotation */}
                  <text x={baseX + Math.min(sc.modules, 14) * (moduleW + 1) + 35} y={sy + moduleH / 2 - 2}
                    fontSize="5" fill="#444">{sc.vocCold}V</text>
                  <text x={baseX + Math.min(sc.modules, 14) * (moduleW + 1) + 35} y={sy + moduleH / 2 + 6}
                    fontSize="5" fill="#444">{sc.current}A</text>
                </g>
              )
            })}

            {/* Roof array wiring label */}
            <text x={baseX} y={95 + strings.length * 50 + 10} fontSize="5.5" fill="#444" fontStyle="italic">
              ROOF ARRAY WIRING
            </text>

            {/* Junction box — pushed lower to avoid overlap */}
            <rect x={baseX + 180} y={95 + strings.length * 50 + 22} width={55} height={22}
              fill="none" stroke="#111" strokeWidth="1" />
            <text x={baseX + 207} y={95 + strings.length * 50 + 35} textAnchor="middle" fontSize="5.5">
              (N) JUNCTION BOX
            </text>
            <text x={baseX + 207} y={95 + strings.length * 50 + 42} textAnchor="middle" fontSize="5" fill="#666">
              600V, NEMA 3
            </text>

            {/* Wire gauge callout from array to JB — offset to avoid JB text */}
            <WireLabel x={baseX + 60} y={95 + strings.length * 50 + 18}
              text="#10 AWG CU PV WIRE, 3/4&quot; EMT TYPE CONDUIT" />
          </g>
        )
      })}

      {/* ── INVERTERS (center, y=420-495) ── */}
      {Array.from({ length: target.inverterCount }, (_, inv) => {
        const cx = inv === 0 ? 250 : 950
        const strings = stringsByInverter[inv] ?? []
        const invY = 420
        const invW = 200
        const invH = 75

        return (
          <g key={`inv-${inv}`}>
            {/* Wire from JB to inverter */}
            <line x1={cx} y1={360} x2={cx} y2={invY} stroke="#111" strokeWidth="1.5" />
            <WireLabel x={cx + 8} y={380}
              text={`(2) #10 AWG CU THWN-2, (1) #6 AWG BARE CU EGC`} />
            <WireLabel x={cx + 8} y={388}
              text={`3/4" EMT TYPE CONDUIT`} />

            {/* DC Disconnect — more vertical space */}
            <Disconnect x={cx} y={375} label="(N) DC DISCONNECT" />

            {/* Inverter box */}
            <rect x={cx - invW / 2} y={invY} width={invW} height={invH}
              fill="none" stroke="#111" strokeWidth="2" />
            <text x={cx} y={invY + 14} textAnchor="middle" fontSize="7" fontWeight="bold">
              (N) {target.inverterModel.toUpperCase().slice(0, 30)}
            </text>
            <text x={cx} y={invY + 24} textAnchor="middle" fontSize="6">
              INVERTER {inv + 1}, 15KW AC OUTPUT, {(target.maxPvPower / 1000).toFixed(0)}KW DC INPUT,
            </text>
            <text x={cx} y={invY + 33} textAnchor="middle" fontSize="6">
              100A RATED, 240V, NEMA 3R
            </text>
            <text x={cx} y={invY + 43} textAnchor="middle" fontSize="5.5" fill="#666">
              {strings.reduce((s, sc) => s + sc.modules, 0)} MODULES = {(strings.reduce((s, sc) => s + sc.modules, 0) * target.panelWattage / 1000).toFixed(2)} kW DC
            </text>
            <text x={cx} y={invY + 52} textAnchor="middle" fontSize="5.5" fill="#666">
              {target.mpptsPerInverter} MPPT, {target.stringsPerMppt} STRINGS/MPPT, MAX {target.maxCurrentPerMppt}A/MPPT
            </text>
            <text x={cx} y={invY + 62} textAnchor="middle" fontSize="5" fill="#999">
              CEC EFFICIENCY: 96.5% | PEAK: 97.5%
            </text>

            {/* Battery stack (left of inverter, 180px gap) */}
            <line x1={cx - invW / 2} y1={invY + invH / 2}
              x2={cx - invW / 2 - 100} y2={invY + invH / 2}
              stroke="#111" strokeWidth="1.5" />
            <WireLabel x={cx - invW / 2 - 98} y={invY + invH / 2 - 8}
              text={`(2) #4/0 AWG CU THWN-2`} />
            <WireLabel x={cx - invW / 2 - 98} y={invY + invH / 2 + 20}
              text={`2" EMT TYPE CONDUIT`} />

            {/* Battery stack box — 180px from inverter center */}
            <rect x={cx - invW / 2 - 180} y={invY - 5} width={70} height={invH + 10}
              fill="none" stroke="#111" strokeWidth="1.5" />
            <text x={cx - invW / 2 - 145} y={invY + 15} textAnchor="middle" fontSize="6" fontWeight="bold">
              (N)({battsPerStack})
            </text>
            <text x={cx - invW / 2 - 145} y={invY + 25} textAnchor="middle" fontSize="5.5">
              {target.batteryModel.toUpperCase()}
            </text>
            <text x={cx - invW / 2 - 145} y={invY + 35} textAnchor="middle" fontSize="5.5">
              {target.batteryCapacity}KWH, 380VDC
            </text>
            <text x={cx - invW / 2 - 145} y={invY + 45} textAnchor="middle" fontSize="5.5">
              IP67, NEMA 3R
            </text>
            <text x={cx - invW / 2 - 145} y={invY + 55} textAnchor="middle" fontSize="5" fill="#666">
              STACK OF {battsPerStack}
            </text>
            <text x={cx - invW / 2 - 145} y={invY + 65} textAnchor="middle" fontSize="5" fill="#666">
              {battsPerStack * target.batteryCapacity} kWh TOTAL
            </text>

            {/* Monitoring Gateway (right of inverter) */}
            <line x1={cx + invW / 2} y1={invY + 20}
              x2={cx + invW / 2 + 25} y2={invY + 20}
              stroke="#111" strokeWidth="1" />
            <rect x={cx + invW / 2 + 25} y={invY + 8} width={90} height={24}
              fill="none" stroke="#111" strokeWidth="0.8" />
            <text x={cx + invW / 2 + 70} y={invY + 18} textAnchor="middle" fontSize="4.5">(N) DCCGRGL</text>
            <text x={cx + invW / 2 + 70} y={invY + 26} textAnchor="middle" fontSize="4.5">DURACELL MONITORING GATEWAY</text>
            <text x={cx + invW / 2 + 70} y={invY + 34} textAnchor="middle" fontSize="3.5" fill="#666">CT CLAMPS ON MAIN SERVICE</text>
            <text x={cx + invW / 2 + 70} y={invY + 39} textAnchor="middle" fontSize="3.5" fill="#666">ENTRANCE CONDUCTORS</text>

            {/* Wireless Bridge (below gateway) */}
            <line x1={cx + invW / 2 + 70} y1={invY + 32}
              x2={cx + invW / 2 + 70} y2={invY + 42}
              stroke="#111" strokeWidth="0.8" strokeDasharray="2,2" />
            <rect x={cx + invW / 2 + 35} y={invY + 42} width={70} height={18}
              fill="none" stroke="#111" strokeWidth="0.8" />
            <text x={cx + invW / 2 + 70} y={invY + 53} textAnchor="middle" fontSize="4.5">(N) WIRELESS BRIDGE</text>

            {/* AC Output from inverter */}
            <line x1={cx} y1={invY + invH} x2={cx} y2={invY + invH + 25}
              stroke="#111" strokeWidth="1.5" />
            <WireLabel x={cx + 8} y={invY + invH + 12}
              text={`#6 AWG CU THWN-2`} />

            {/* AC Disconnect — more space */}
            <Disconnect x={cx} y={invY + invH + 30} label="(N) AC DISCONNECT, 200A/2P, 240V" />

            {/* Wire down to bus */}
            <line x1={cx} y1={invY + invH + 42} x2={cx} y2={640}
              stroke="#111" strokeWidth="1.5" />
            <WireLabel x={cx + 8} y={invY + invH + 58}
              text={`(2) #4 AWG CU THWN-2, (1) #8 AWG CU EGC`} />
            <WireLabel x={cx + 8} y={invY + invH + 66}
              text={`1-1/4" EMT TYPE CONDUIT`} />

            {/* PV Breaker on bus */}
            <Breaker x={cx} y={645} label={`(N) 100A BACKFEED`} amps="BREAKER" />
          </g>
        )
      })}

      {/* ── EXISTING HOME PANEL BUS BAR (y=665) ── */}
      <line x1="80" y1={665} x2={W - 250} y2={665} stroke="#111" strokeWidth="3" />
      <text x={(W - 250) / 2 + 40} y={658} textAnchor="middle" fontSize="7" fontWeight="bold">
        (E) EXISTING HOME ELECTRICAL PANEL
      </text>
      <text x={(W - 250) / 2 + 40} y={678} textAnchor="middle" fontSize="6" fill="#666">
        200A RATED, 240V, SINGLE PHASE
      </text>

      {/* Main breaker (left end of bus) */}
      <line x1="60" y1={665} x2="60" y2={710} stroke="#111" strokeWidth="1.5" />
      <Breaker x={60} y={690} label="(E) MAIN" amps="200A" />
      <text x="60" y={730} textAnchor="middle" fontSize="5.5">TO LOADS</text>

      {/* Existing PV breaker */}
      <line x1="500" y1={665} x2="500" y2={710} stroke="#111" strokeWidth="1" strokeDasharray="4,3" />
      <Breaker x={500} y={690} label="(E) 40A PV" amps="BREAKER" />
      <text x="500" y={730} textAnchor="middle" fontSize="5" fill="#666">(E) EXISTING ENPHASE</text>
      <text x="500" y={738} textAnchor="middle" fontSize="5" fill="#666">IQ7PLUS SYSTEM</text>

      {/* Generator Ready Circuit (future) */}
      <line x1="650" y1={665} x2="650" y2={720} stroke="#111" strokeWidth="1" strokeDasharray="4,3" />
      <rect x="620" y={720} width="60" height="24" fill="none" stroke="#111" strokeWidth="1" strokeDasharray="4,3" />
      <text x="650" y={733} textAnchor="middle" fontSize="5" fill="#666">(FUTURE) 100A</text>
      <text x="650" y={740} textAnchor="middle" fontSize="5" fill="#666">AC INPUT</text>
      <text x="650" y={755} textAnchor="middle" fontSize="4.5" fill="#999">FUTURE PLUG-AND-PLAY CONNECTION</text>
      <text x="650" y={763} textAnchor="middle" fontSize="4.5" fill="#999">FOR 22kW NATURAL GAS GENERATOR</text>

      {/* ── GENERATION DISCONNECT → RGM → METER → GRID (right side) ── */}
      <line x1={W - 250} y1={665} x2={W - 200} y2={665} stroke="#111" strokeWidth="1.5" />

      {/* Generation Disconnect */}
      <rect x={W - 210} y={650} width={70} height={28} fill="none" stroke="#111" strokeWidth="1" />
      <text x={W - 175} y={662} textAnchor="middle" fontSize="5.5">(N) GENERATION</text>
      <text x={W - 175} y={670} textAnchor="middle" fontSize="5.5">DISCONNECT</text>

      {/* Wire to RGM */}
      <line x1={W - 140} y1={665} x2={W - 120} y2={665} stroke="#111" strokeWidth="1.5" />

      {/* Revenue Grade Meter */}
      <rect x={W - 120} y={652} width={50} height={25} fill="none" stroke="#111" strokeWidth="0.8" />
      <text x={W - 95} y={662} textAnchor="middle" fontSize="4">(N) RGM</text>
      <text x={W - 95} y={670} textAnchor="middle" fontSize="3.5">PC-PRO-RGM-W2-BA-L</text>

      {/* Wire to utility meter */}
      <line x1={W - 70} y1={665} x2={W - 55} y2={665} stroke="#111" strokeWidth="1.5" />

      {/* Utility Meter circle */}
      <circle cx={W - 35} cy={665} r="20" fill="none" stroke="#111" strokeWidth="1.5" />
      <text x={W - 35} y={662} textAnchor="middle" fontSize="7" fontWeight="bold">M</text>
      <text x={W - 35} y={672} textAnchor="middle" fontSize="5.5">kWh</text>

      {/* Labels for meter */}
      <text x={W - 35} y={640} textAnchor="middle" fontSize="5.5" fill="#666">
        (E) BIDIRECTIONAL
      </text>
      <text x={W - 35} y={633} textAnchor="middle" fontSize="5.5" fill="#666">
        UTILITY METER
      </text>

      {/* Wire to grid */}
      <line x1={W - 15} y1={665} x2={W - 12} y2={665} stroke="#111" strokeWidth="1.5" />
      <text x={W - 25} y={700} fontSize="6" fill="#666">TO UTILITY</text>
      <text x={W - 25} y={709} fontSize="6" fill="#666">GRID</text>
      <text x={W - 25} y={720} fontSize="5" fill="#999">CENTERPOINT</text>
      <text x={W - 25} y={728} fontSize="5" fill="#999">ENERGY</text>

      {/* 10 FT MAX notation */}
      <line x1={W - 230} y1={625} x2={W - 15} y2={625} stroke="#111" strokeWidth="0.5" />
      <text x={W - 120} y={622} textAnchor="middle" fontSize="6" fontWeight="bold">10&apos; MAX</text>
      <line x1={W - 230} y1={623} x2={W - 230} y2={630} stroke="#111" strokeWidth="0.5" />
      <line x1={W - 15} y1={623} x2={W - 15} y2={630} stroke="#111" strokeWidth="0.5" />

      {/* ── GROUND SYSTEM ── */}
      <line x1="120" y1={665} x2="120" y2={740} stroke="#111" strokeWidth="1" />
      <line x1="112" y1={740} x2="128" y2={740} stroke="#111" strokeWidth="1.5" />
      <line x1="114" y1={744} x2="126" y2={744} stroke="#111" strokeWidth="1.5" />
      <line x1="116" y1={748} x2="124" y2={748} stroke="#111" strokeWidth="1.5" />
      <text x="135" y={740} fontSize="5.5">EXISTING GROUNDING</text>
      <text x="135" y={748} fontSize="5.5">ELECTRODE SYSTEM</text>
      <text x="135" y={756} fontSize="5" fill="#666">NEC 250.50, 250.52(A)</text>

      {/* ── NOTES SECTION (bottom left) ── */}
      <rect x="20" y={H - 190} width={W - 340} height={178} fill="none" stroke="#111" strokeWidth="0.5" />
      <text x="30" y={H - 175} fontSize="7" fontWeight="bold">NOTES:</text>
      {[
        '1. ALL ELECTRICAL MATERIALS SHALL BE NEW AND LISTED BY RECOGNIZED TESTING LABORATORY.',
        '2. OUTDOOR EQUIPMENT SHALL BE AT LEAST NEMA 3R RATED.',
        '3. ALL METALLIC EQUIPMENT SHALL BE GROUNDED.',
        '4. ALL SPECIFIC WIRING IS BASED ON THE USE OF COPPER.',
        `5. PV SYSTEM SIZE: ${results.newSystemDc} kW DC / ${target.inverterCount * 15} kW AC.`,
        '6. INVERTER IS EQUIPPED W/ INTEGRATED GFDI, PROVIDING GROUND FAULT PROTECTION.',
        '7. ALL CONDUITS SHALL BE COPPER AND 90 DEG RATED.',
        `8. BATTERY SYSTEM: (${target.batteryCount}) ${target.batteryModel.toUpperCase()}, ${results.newTotalStorage} kWh TOTAL.`,
        '9. REQUIRES AC SOFT STARTER KITS.',
        '10. REQUIRES RIGID RACK FOR BATTERY MOUNTING.',
        `11. RACKING: ${target.rackingModel.toUpperCase()}`,
        '12. ALL WORK SHALL BE IN ACCORD WITH THE 2020 NEC WITH SPECIAL EMPHASIS ON ARTICLE 690.',
        'NOTE: PCS CONTROLLED CURRENT SETTING: 200A.',
        'NOTE: STRING CALCULATIONS REQUIRE PE REVIEW BEFORE PERMITTING.',
      ].map((note, i) => (
        <text key={i} x="30" y={H - 163 + i * 11} fontSize="5.5" fill="#333">{note}</text>
      ))}

      {/* ── BATTERY SCOPE BOX (top right) ── */}
      <rect x={W - 280} y="16" width="265" height="55" fill="none" stroke="#111" strokeWidth="1" />
      <text x={W - 270} y="29" fontSize="6" fontWeight="bold">BATTERY SCOPE</text>
      <text x={W - 270} y="39" fontSize="5.5">(N)({target.batteryCount}) {target.batteryModel.toUpperCase()}</text>
      <text x={W - 270} y="49" fontSize="5.5">{target.batteryCapacity}KWH, 380VDC, IP67, NEMA 3R</text>
      <text x={W - 270} y="59" fontSize="5.5">TOTAL STORAGE: {results.newTotalStorage} kWh | STACKS: {Math.ceil(target.batteryCount / battsPerStack)} x {battsPerStack}</text>

      {/* ── EXISTING SYSTEM NOTE ── */}
      <rect x="480" y={760} width="180" height="30" fill="none" stroke="#111" strokeWidth="0.5" strokeDasharray="4,3" />
      <text x="490" y={774} fontSize="5.5" fill="#666">(E)(20) SILFAB SOLAR SIL-370 HC (370W)</text>
      <text x="490" y={783} fontSize="5.5" fill="#666">(E)(20) ENPHASE IQ7PLUS-72-2-US (240V)</text>

      {/* ── SHEET INFO ── */}
      <text x={W - 30} y={H - 105} textAnchor="end" fontSize="6" fill="#666">SHEET PV-5</text>
      <text x={W - 30} y={H - 96} textAnchor="end" fontSize="5" fill="#999">SCALE: NTS</text>
    </svg>
  )
}
