/**
 * Single-Line Diagram (SLD) DXF Generator
 *
 * Produces a professional electrical single-line diagram on an ANSI D
 * sheet (34" x 22") suitable for PE review. The output is a valid DXF
 * file that opens in AutoCAD, LibreCAD, or any DXF viewer.
 *
 * Generated by MicroGRID for TriSMART Solar / MicroGRID Energy.
 */

import { DxfBuilder } from './dxf-generator'

// ── Public interface ──────────────────────────────────────────────────

export interface SldStringConfig {
  mppt: number
  string: number
  modules: number
  vocCold: number
  vmpNominal: number
  current: number
  roofFaceIndex: number
}

export interface SldInput {
  projectName: string
  address: string
  // Panel specs
  panelModel: string
  panelWattage: number
  panelCount: number
  // Inverter specs
  inverterModel: string
  inverterCount: number
  inverterAcPower: number // kW per inverter
  maxPvPower: number
  mpptsPerInverter: number
  stringsPerMppt: number
  // Battery specs
  batteryModel: string
  batteryCount: number
  batteryCapacity: number // kWh per battery
  batteriesPerStack: number
  // String configs
  strings: SldStringConfig[]
  // System totals
  systemDcKw: number
  totalStorageKwh: number
  // Racking
  rackingModel: string
}

// ── Layout constants (inches, origin at bottom-left) ──────────────────

const SHEET_W = 34
const SHEET_H = 22
const MARGIN = 0.5

// Functional zones (Y ranges)
const Y_PV_TOP = 20.0
const Y_PV_BOT = 16.5
const Y_JB = 15.0
const Y_DCDISC = 13.5
const Y_INV_TOP = 11.5
const Y_INV_BOT = 8.5
const Y_BATT_TOP = 11.5
const Y_BATT_BOT = 8.5
const Y_AC_DISC = 7.0
const Y_BUS_TOP = 5.5
const Y_BUS_BOT = 4.0
const Y_UTIL = 2.5

// Layers
const L_PV = 'PV'
const L_BATT = 'BATTERY'
const L_AC = 'AC'
const L_EQ = 'EQUIPMENT'
const L_ANN = 'ANNOTATION'
const L_BORDER = 'BORDER'

// Text sizes
const TXT_LG = 0.18
const TXT_MD = 0.14
const TXT_SM = 0.10
const TXT_XS = 0.08

// ── Helpers ───────────────────────────────────────────────────────────

function fmtKw(w: number): string {
  return (w / 1000).toFixed(2)
}

function today(): string {
  const d = new Date()
  const mm = String(d.getMonth() + 1).padStart(2, '0')
  const dd = String(d.getDate()).padStart(2, '0')
  return `${mm}/${dd}/${d.getFullYear()}`
}

// ── Generator ─────────────────────────────────────────────────────────

export function generateSingleLineDxf(input: SldInput): string {
  const dxf = new DxfBuilder()

  // Register layers
  dxf.addLayer(L_PV, 2)      // yellow
  dxf.addLayer(L_BATT, 3)    // green
  dxf.addLayer(L_AC, 5)      // blue
  dxf.addLayer(L_EQ, 7)      // white
  dxf.addLayer(L_ANN, 8)     // gray
  dxf.addLayer(L_BORDER, 7)  // white

  // ── 1. Drawing border & title block ─────────────────────────────────
  drawBorder(dxf)
  drawTitleBlock(dxf, input)

  // ── 2. PV array strings ─────────────────────────────────────────────
  drawPvArrays(dxf, input)

  // ── 3. Junction boxes ───────────────────────────────────────────────
  drawJunctionBoxes(dxf, input)

  // ── 4. DC disconnects ───────────────────────────────────────────────
  drawDcDisconnects(dxf, input)

  // ── 5. Inverters ────────────────────────────────────────────────────
  drawInverters(dxf, input)

  // ── 6. Battery stacks ───────────────────────────────────────────────
  drawBatteryStacks(dxf, input)

  // ── 7. AC output & disconnect ───────────────────────────────────────
  drawAcOutput(dxf, input)

  // ── 8. Smart panel / main bus ───────────────────────────────────────
  drawMainBus(dxf, input)

  // ── 9. Utility connection ───────────────────────────────────────────
  drawUtilityConnection(dxf, input)

  // ── 10. Notes ───────────────────────────────────────────────────────
  drawNotes(dxf, input)

  return dxf.toString()
}

// ── Drawing sections ──────────────────────────────────────────────────

function drawBorder(dxf: DxfBuilder): void {
  // Outer border
  dxf.addRect(MARGIN, MARGIN, SHEET_W - 2 * MARGIN, SHEET_H - 2 * MARGIN, L_BORDER)
  // Inner border (0.1" inset)
  dxf.addRect(MARGIN + 0.1, MARGIN + 0.1, SHEET_W - 2 * MARGIN - 0.2, SHEET_H - 2 * MARGIN - 0.2, L_BORDER)
}

function drawTitleBlock(dxf: DxfBuilder, inp: SldInput): void {
  const tbX = SHEET_W - MARGIN - 6.5
  const tbY = MARGIN + 0.2
  const tbW = 6.3
  const tbH = 2.4

  // Title block outline
  dxf.addRect(tbX, tbY, tbW, tbH, L_BORDER)

  // Horizontal dividers
  dxf.addLine(tbX, tbY + 0.5, tbX + tbW, tbY + 0.5, L_BORDER)
  dxf.addLine(tbX, tbY + 1.0, tbX + tbW, tbY + 1.0, L_BORDER)
  dxf.addLine(tbX, tbY + 1.5, tbX + tbW, tbY + 1.5, L_BORDER)
  dxf.addLine(tbX, tbY + 1.9, tbX + tbW, tbY + 1.9, L_BORDER)

  // Title text
  dxf.addText(tbX + 0.15, tbY + 2.05, TXT_LG, 'ELECTRICAL SINGLE-LINE DIAGRAM', L_ANN)
  dxf.addText(tbX + 0.15, tbY + 1.58, TXT_MD, inp.projectName, L_ANN)
  dxf.addText(tbX + 0.15, tbY + 1.08, TXT_SM, inp.address, L_ANN)
  dxf.addText(tbX + 0.15, tbY + 0.58, TXT_SM, `SYSTEM: ${inp.systemDcKw.toFixed(2)} kW DC  |  ${inp.totalStorageKwh.toFixed(1)} kWh STORAGE`, L_ANN)
  dxf.addText(tbX + 0.15, tbY + 0.30, TXT_XS, `DATE: ${today()}`, L_ANN)
  dxf.addText(tbX + 3.0, tbY + 0.30, TXT_XS, 'SHEET 1 OF 1', L_ANN)
  dxf.addText(tbX + 0.15, tbY + 0.10, TXT_XS, 'GENERATED BY MicroGRID \u2014 FOR PE REVIEW ONLY', L_ANN)
}

// ── PV Arrays ─────────────────────────────────────────────────────────

function drawPvArrays(dxf: DxfBuilder, inp: SldInput): void {
  const totalStrings = inp.strings.length
  if (totalStrings === 0) return

  // Distribute strings across available width
  const availW = 26
  const startX = 2.0
  const spacing = Math.min(availW / totalStrings, 4.0)

  for (let i = 0; i < totalStrings; i++) {
    const s = inp.strings[i]
    const cx = startX + i * spacing + spacing / 2
    const y = Y_PV_TOP

    // Draw small rectangles representing modules in the string
    const moduleW = 0.15
    const moduleH = 0.20
    const modulesPerRow = Math.min(s.modules, 6)
    const rows = Math.ceil(s.modules / modulesPerRow)

    const blockW = modulesPerRow * (moduleW + 0.04) - 0.04
    const blockStartX = cx - blockW / 2

    for (let r = 0; r < rows; r++) {
      const modulesInRow = r === rows - 1 ? s.modules - r * modulesPerRow : modulesPerRow
      for (let m = 0; m < modulesInRow; m++) {
        const mx = blockStartX + m * (moduleW + 0.04)
        const my = y - r * (moduleH + 0.06)
        dxf.addRect(mx, my, moduleW, moduleH, L_PV)
      }
      // Series connection lines between modules in row
      if (modulesInRow > 1) {
        for (let m = 0; m < modulesInRow - 1; m++) {
          const x1 = blockStartX + m * (moduleW + 0.04) + moduleW
          const x2 = blockStartX + (m + 1) * (moduleW + 0.04)
          const lineY = y - r * (moduleH + 0.06) + moduleH / 2
          dxf.addLine(x1, lineY, x2, lineY, L_PV)
        }
      }
    }

    // String label
    const watts = s.modules * inp.panelWattage
    const label = `STRING ${i + 1}: ${s.modules}x ${inp.panelModel} ${inp.panelWattage}W`
    dxf.addText(cx, y - rows * (moduleH + 0.06) - 0.10, TXT_XS, label, L_ANN, { halign: 'center' })
    dxf.addText(cx, y - rows * (moduleH + 0.06) - 0.24, TXT_XS, `= ${(watts / 1000).toFixed(2)} kW DC`, L_ANN, { halign: 'center' })

    // Voc / Vmp / Isc annotation
    dxf.addText(
      cx, y - rows * (moduleH + 0.06) - 0.38, TXT_XS,
      `Voc=${s.vocCold.toFixed(0)}V  Vmp=${s.vmpNominal.toFixed(0)}V  Isc=${s.current.toFixed(1)}A`,
      L_ANN, { halign: 'center' }
    )

    // Roof face label
    dxf.addText(
      cx, y - rows * (moduleH + 0.06) - 0.52, TXT_XS,
      `ROOF FACE ${s.roofFaceIndex + 1}  |  MPPT ${s.mppt}`,
      L_ANN, { halign: 'center' }
    )

    // RSD symbol (small box with "RSD")
    const rsdY = y - rows * (moduleH + 0.06) - 0.80
    dxf.addRect(cx - 0.20, rsdY, 0.40, 0.20, L_PV)
    dxf.addText(cx, rsdY + 0.04, TXT_XS, 'RSD', L_PV, { halign: 'center' })

    // Wire down to junction box zone
    const wireTopY = rsdY
    const wireBotY = Y_JB + 0.35
    dxf.addLine(cx, wireTopY, cx, wireBotY, L_PV)

    // Wire callout
    dxf.addText(cx + 0.08, (wireTopY + wireBotY) / 2, TXT_XS, '#10 AWG CU PV WIRE', L_ANN)
  }

  // Section title
  dxf.addText(1.2, Y_PV_TOP + 0.30, TXT_MD, '(N) PV ARRAY', L_ANN)
  dxf.addText(1.2, Y_PV_TOP + 0.10, TXT_XS, `${inp.panelCount}x ${inp.panelModel} ${inp.panelWattage}W  |  ${inp.rackingModel}`, L_ANN)
}

// ── Junction Boxes ────────────────────────────────────────────────────

function drawJunctionBoxes(dxf: DxfBuilder, inp: SldInput): void {
  if (inp.strings.length === 0) return

  // Group strings by inverter
  const stringsPerInv = Math.ceil(inp.strings.length / inp.inverterCount)
  const availW = 26
  const startX = 2.0
  const spacing = Math.min(availW / inp.strings.length, 4.0)

  for (let inv = 0; inv < inp.inverterCount; inv++) {
    const firstStr = inv * stringsPerInv
    const lastStr = Math.min((inv + 1) * stringsPerInv - 1, inp.strings.length - 1)
    if (firstStr > inp.strings.length - 1) break

    const leftX = startX + firstStr * spacing + spacing / 2 - 0.4
    const rightX = startX + lastStr * spacing + spacing / 2 + 0.4
    const jbW = rightX - leftX
    const jbCx = leftX + jbW / 2

    // Junction box rectangle
    dxf.addRect(leftX, Y_JB, jbW, 0.35, L_EQ)
    dxf.addText(jbCx, Y_JB + 0.10, TXT_XS, `(N) JUNCTION BOX, 600V, NEMA 3R`, L_ANN, { halign: 'center' })

    // Wire down to DC disconnect
    dxf.addLine(jbCx, Y_JB, jbCx, Y_DCDISC + 0.35, L_PV)
    dxf.addText(jbCx + 0.08, (Y_JB + Y_DCDISC + 0.35) / 2, TXT_XS, '#10 AWG CU, 3/4" EMT', L_ANN)
  }
}

// ── DC Disconnects ────────────────────────────────────────────────────

function drawDcDisconnects(dxf: DxfBuilder, inp: SldInput): void {
  const stringsPerInv = Math.ceil(inp.strings.length / inp.inverterCount)
  const availW = 26
  const startX = 2.0
  const spacing = Math.min(availW / Math.max(inp.strings.length, 1), 4.0)

  for (let inv = 0; inv < inp.inverterCount; inv++) {
    const firstStr = inv * stringsPerInv
    const lastStr = Math.min((inv + 1) * stringsPerInv - 1, inp.strings.length - 1)
    if (firstStr > inp.strings.length - 1) break

    const leftX = startX + firstStr * spacing + spacing / 2 - 0.4
    const rightX = startX + lastStr * spacing + spacing / 2 + 0.4
    const cx = (leftX + rightX) / 2

    // DC disconnect box
    dxf.addRect(cx - 0.5, Y_DCDISC, 1.0, 0.35, L_EQ)
    dxf.addDisconnectSymbol(cx, Y_DCDISC + 0.18, L_PV)
    dxf.addText(cx, Y_DCDISC - 0.15, TXT_XS, '(N) DC DISCONNECT', L_ANN, { halign: 'center' })
    dxf.addText(cx, Y_DCDISC - 0.28, TXT_XS, 'FUSED, 600V DC', L_ANN, { halign: 'center' })

    // Wire down to inverter
    dxf.addLine(cx, Y_DCDISC, cx, Y_INV_TOP + 0.05, L_PV)
    dxf.addText(cx + 0.08, (Y_DCDISC + Y_INV_TOP) / 2, TXT_XS, '#10 AWG CU PV WIRE, 3/4" EMT', L_ANN)
  }
}

// ── Inverters ─────────────────────────────────────────────────────────

function getInverterCenterX(inv: number, total: number): number {
  const availW = 22
  const startX = 5.0
  const spacing = total > 1 ? availW / total : 0
  return startX + inv * spacing + spacing / 2
}

function drawInverters(dxf: DxfBuilder, inp: SldInput): void {
  for (let inv = 0; inv < inp.inverterCount; inv++) {
    const cx = getInverterCenterX(inv, inp.inverterCount)
    const invW = 3.0
    const invH = Y_INV_TOP - Y_INV_BOT
    const invX = cx - invW / 2
    const invY = Y_INV_BOT

    // Inverter box
    dxf.addRect(invX, invY, invW, invH, L_EQ)

    // Inner label
    dxf.addText(cx, invY + invH - 0.25, TXT_SM, `(N) ${inp.inverterModel}`, L_ANN, { halign: 'center' })
    dxf.addText(cx, invY + invH - 0.50, TXT_XS, `HYBRID INVERTER`, L_ANN, { halign: 'center' })
    dxf.addText(cx, invY + invH - 0.70, TXT_XS, `${inp.inverterAcPower} kW AC  |  ${inp.maxPvPower} kW PV MAX`, L_ANN, { halign: 'center' })
    dxf.addText(cx, invY + invH - 0.90, TXT_XS, `${inp.mpptsPerInverter} MPPT  |  240/120V SPLIT PHASE`, L_ANN, { halign: 'center' })
    dxf.addText(cx, invY + invH - 1.10, TXT_XS, 'NEMA 3R', L_ANN, { halign: 'center' })

    // DC input label (left side)
    dxf.addText(invX - 0.05, invY + invH / 2 + 0.10, TXT_XS, 'DC IN', L_PV)
    dxf.addText(invX - 0.05, invY + invH / 2 - 0.05, TXT_XS, `${inp.mpptsPerInverter} MPPT`, L_PV)

    // AC output label (right side)
    dxf.addText(invX + invW + 0.05, invY + invH / 2 + 0.10, TXT_XS, 'AC OUT', L_AC)
    dxf.addText(invX + invW + 0.05, invY + invH / 2 - 0.05, TXT_XS, '240V', L_AC)

    // Battery port label (bottom-left)
    dxf.addText(invX + 0.10, invY - 0.15, TXT_XS, 'BATT PORT', L_BATT)

    // Wire from inverter AC output down to AC disconnect
    dxf.addLine(cx, invY, cx, Y_AC_DISC + 0.35, L_AC)
    dxf.addText(cx + 0.08, (invY + Y_AC_DISC + 0.35) / 2, TXT_XS, '#6 AWG CU THWN-2, 1" EMT', L_ANN)
  }
}

// ── Battery Stacks ────────────────────────────────────────────────────

function drawBatteryStacks(dxf: DxfBuilder, inp: SldInput): void {
  if (inp.batteryCount === 0) return

  const stackCount = Math.ceil(inp.batteryCount / inp.batteriesPerStack)
  const battsPerInv = Math.ceil(stackCount / inp.inverterCount)

  for (let inv = 0; inv < inp.inverterCount; inv++) {
    const invCx = getInverterCenterX(inv, inp.inverterCount)
    const battBaseX = invCx - 3.8

    for (let s = 0; s < battsPerInv; s++) {
      const stackIdx = inv * battsPerInv + s
      if (stackIdx >= stackCount) break

      const battsInStack = stackIdx === stackCount - 1
        ? inp.batteryCount - stackIdx * inp.batteriesPerStack
        : inp.batteriesPerStack

      const stackX = battBaseX + s * 1.6
      const stackY = Y_BATT_BOT + 0.2
      const battW = 1.2
      const battH = 0.25
      const gap = 0.04

      // Draw individual battery cells in stack
      for (let b = 0; b < battsInStack; b++) {
        const by = stackY + b * (battH + gap)
        dxf.addRect(stackX, by, battW, battH, L_BATT)
        // Small +/- terminals
        dxf.addText(stackX + 0.05, by + 0.06, TXT_XS, '+', L_BATT)
        dxf.addText(stackX + battW - 0.12, by + 0.06, TXT_XS, '-', L_BATT)
      }

      // Stack label
      const stackKwh = battsInStack * inp.batteryCapacity
      dxf.addText(
        stackX + battW / 2, stackY - 0.15, TXT_XS,
        `(N)(${battsInStack}) ${inp.batteryModel}`,
        L_ANN, { halign: 'center' }
      )
      dxf.addText(
        stackX + battW / 2, stackY - 0.30, TXT_XS,
        `${inp.batteryCapacity} kWh EA, STACK = ${stackKwh.toFixed(1)} kWh`,
        L_ANN, { halign: 'center' }
      )

      // Wire from stack to inverter battery port
      const wireFromX = stackX + battW
      const wireY = stackY + (battsInStack * (battH + gap)) / 2
      dxf.addLine(wireFromX, wireY, invCx - 1.5, wireY, L_BATT)
      dxf.addLine(invCx - 1.5, wireY, invCx - 1.5, Y_INV_BOT + 0.3, L_BATT)

      // Wire callout
      dxf.addText(
        (wireFromX + invCx - 1.5) / 2, wireY + 0.08, TXT_XS,
        '#8 AWG CU, 1" EMT', L_ANN, { halign: 'center' }
      )
    }
  }

  // Section label
  dxf.addText(1.2, Y_BATT_TOP + 0.15, TXT_SM, `(N) BATTERY STORAGE: ${inp.totalStorageKwh.toFixed(1)} kWh TOTAL`, L_ANN)
  dxf.addText(1.2, Y_BATT_TOP - 0.05, TXT_XS, 'REQUIRES RIGID RACK FOR BATTERY MOUNTING', L_ANN)
}

// ── AC Output & Disconnect ────────────────────────────────────────────

function drawAcOutput(dxf: DxfBuilder, inp: SldInput): void {
  for (let inv = 0; inv < inp.inverterCount; inv++) {
    const cx = getInverterCenterX(inv, inp.inverterCount)

    // AC disconnect box
    dxf.addRect(cx - 0.6, Y_AC_DISC, 1.2, 0.35, L_EQ)
    dxf.addDisconnectSymbol(cx, Y_AC_DISC + 0.18, L_AC)
    dxf.addText(cx, Y_AC_DISC - 0.15, TXT_XS, '(N) AC DISCONNECT', L_ANN, { halign: 'center' })
    dxf.addText(cx, Y_AC_DISC - 0.28, TXT_XS, '200A, 240V, NEMA 3R', L_ANN, { halign: 'center' })

    // Wire down to main bus
    dxf.addLine(cx, Y_AC_DISC, cx, Y_BUS_TOP + 0.10, L_AC)
    dxf.addText(cx + 0.08, (Y_AC_DISC + Y_BUS_TOP) / 2, TXT_XS, '#4 AWG CU THWN-2, 1-1/4" EMT', L_ANN)
  }
}

// ── Smart Panel / Main Bus ────────────────────────────────────────────

function drawMainBus(dxf: DxfBuilder, inp: SldInput): void {
  const busX1 = 3.0
  const busX2 = 29.0
  const busY = (Y_BUS_TOP + Y_BUS_BOT) / 2

  // Panel enclosure
  dxf.addRect(busX1 - 0.3, Y_BUS_BOT, busX2 - busX1 + 0.6, Y_BUS_TOP - Y_BUS_BOT, L_EQ)

  // Bus bar (thick double line)
  dxf.addLine(busX1, busY + 0.03, busX2, busY + 0.03, L_AC)
  dxf.addLine(busX1, busY - 0.03, busX2, busY - 0.03, L_AC)

  // Panel label
  dxf.addText(busX1 + 0.3, Y_BUS_TOP - 0.18, TXT_SM, '(N) SMART ELECTRICAL PANEL, 260A BUS, 240/120V, NEMA 3R', L_ANN)

  // Breakers along bus
  const breakerSpacing = (busX2 - busX1 - 2) / (inp.inverterCount + 2)
  let bx = busX1 + 1.5

  // Main breaker
  dxf.addBreakerSymbol(bx, busY, L_AC)
  dxf.addText(bx, busY - 0.35, TXT_XS, '200A', L_ANN, { halign: 'center' })
  dxf.addText(bx, busY - 0.48, TXT_XS, 'MAIN', L_ANN, { halign: 'center' })
  bx += breakerSpacing

  // PV breaker(s) — one per inverter
  for (let inv = 0; inv < inp.inverterCount; inv++) {
    dxf.addBreakerSymbol(bx, busY, L_AC)
    dxf.addText(bx, busY - 0.35, TXT_XS, '125A PV', L_ANN, { halign: 'center' })
    dxf.addText(bx, busY - 0.48, TXT_XS, `INV ${inv + 1}`, L_ANN, { halign: 'center' })

    // Vertical stub up from breaker to where AC wire comes in
    const invCx = getInverterCenterX(inv, inp.inverterCount)
    dxf.addLine(bx, busY + 0.03, bx, Y_BUS_TOP + 0.10, L_AC)
    // Horizontal jog if breaker not aligned with inverter
    if (Math.abs(bx - invCx) > 0.1) {
      dxf.addLine(bx, Y_BUS_TOP + 0.10, invCx, Y_BUS_TOP + 0.10, L_AC)
    }
    bx += breakerSpacing
  }

  // Ground symbol at end of bus
  dxf.addGroundSymbol(busX2 - 0.5, busY - 0.03, L_EQ)
  dxf.addText(busX2 - 0.5, busY - 0.55, TXT_XS, 'GND', L_ANN, { halign: 'center' })

  // Wire from main breaker out to utility
  dxf.addLine(busX1 + 1.5, busY - 0.03, busX1 + 1.5, Y_UTIL + 0.50, L_AC)
  dxf.addLine(busX1 + 1.5, Y_UTIL + 0.50, busX2 + 1.0, Y_UTIL + 0.50, L_AC)
}

// ── Utility Connection ────────────────────────────────────────────────

function drawUtilityConnection(dxf: DxfBuilder, inp: SldInput): void {
  const utilX = 30.0
  const utilY = Y_UTIL

  // Generation disconnect
  dxf.addRect(utilX - 0.6, utilY + 0.80, 1.2, 0.35, L_EQ)
  dxf.addDisconnectSymbol(utilX, utilY + 0.98, L_AC)
  dxf.addText(utilX, utilY + 0.65, TXT_XS, '(N) GEN DISCONNECT', L_ANN, { halign: 'center' })

  // Wire down to meter
  dxf.addLine(utilX, utilY + 0.80, utilX, utilY + 0.50, L_AC)

  // Meter symbol
  dxf.addMeterSymbol(utilX, utilY + 0.25, L_EQ)

  // Wire down from meter
  dxf.addLine(utilX, utilY, utilX, utilY - 0.25, L_AC)

  // Utility label
  dxf.addText(utilX, utilY - 0.40, TXT_SM, 'UTILITY GRID', L_ANN, { halign: 'center' })
  dxf.addText(utilX, utilY - 0.58, TXT_XS, 'POINT OF INTERCONNECTION', L_ANN, { halign: 'center' })

  // Ground at utility
  dxf.addGroundSymbol(utilX + 0.6, utilY - 0.25, L_EQ)

  // Horizontal connection line from bus
  dxf.addLine(utilX, utilY + 0.50, 30.0 + 1.0, utilY + 0.50, L_AC)
}

// ── Notes Section ─────────────────────────────────────────────────────

function drawNotes(dxf: DxfBuilder, inp: SldInput): void {
  const notesX = 1.2
  let y = 3.4

  dxf.addText(notesX, y, TXT_MD, 'GENERAL NOTES:', L_ANN)
  y -= 0.25

  const notes = [
    `1. PCS CONTROLLED CURRENT SETTING: 200A`,
    `2. ALL WIRING PER NEC 2023, ARTICLE 690 (SOLAR PV) & 706 (ESS)`,
    `3. PV WIRE SIZING PER NEC 690.8 \u2014 125% CONTINUOUS CURRENT CORRECTION`,
    `4. AC WIRE SIZING PER NEC 310.16 AT 75\u00b0C COLUMN`,
    `5. EQUIPMENT GROUNDING PER NEC 250.122`,
    `6. RAPID SHUTDOWN PER NEC 690.12 \u2014 COMPLIANT MODULES WITH MODULE-LEVEL RSD`,
    `7. ARC-FAULT PROTECTION PER NEC 690.11`,
    `8. REQUIRES AC SOFT STARTER KITS FOR INVERTER(S)`,
    `9. REQUIRES RIGID RACK FOR BATTERY MOUNTING \u2014 ${inp.rackingModel}`,
    `10. SYSTEM DC CAPACITY: ${inp.systemDcKw.toFixed(2)} kW  |  AC CAPACITY: ${(inp.inverterAcPower * inp.inverterCount).toFixed(1)} kW`,
    `11. TOTAL ENERGY STORAGE: ${inp.totalStorageKwh.toFixed(1)} kWh (${inp.batteryCount}x ${inp.batteryModel})`,
    `12. FOR PE REVIEW \u2014 NOT FOR CONSTRUCTION`,
  ]

  for (const note of notes) {
    dxf.addText(notesX, y, TXT_XS, note, L_ANN)
    y -= 0.18
  }
}
